# Directories
DATA_FOLDER_NAME = '../data/'
PRICES_FOLDER_NAME = DATA_FOLDER_NAME + 'prices'
CANDLE_FOLDER_NAME = DATA_FOLDER_NAME + 'candles'
MERGED_DIRECTORY_NAME = DATA_FOLDER_NAME + 'merged'

# Files
CANDLE_FILE_NAME = 'candle'
PRICES_FILE_NAME = 'price'
